name: CI

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build the project
        run: ./gradlew packageDmg
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: PiStats-MacOS
          path: $GITHUB_WORKSPACE/desktop/build/compose/binaries/main/dmg/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build the project
        run: ./gradlew packageDeb
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: PiStats-Linux
          path: $GITHUB_WORKSPACE/desktop/build/compose/binaries/main/deb/

  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build the project
        run: ./gradlew packageMsi
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: PiStats-Windows
          path: $GITHUB_WORKSPACE\desktop\build\compose\binaries\main\msi\

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Build the project
        run: ./gradlew assembleDebug
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: PiStats-Android
          path: $GITHUB_WORKSPACE/android/build/outputs/apk/debug/android-debug.apk